### ISSUE TITLE
Investigate prescaling SW TP generation

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/fdreadoutlibs#73]
We have a problem where the nodes cannot keep up with TP generation in SWTP mode. We can either run with fewer links, as we have been doing, or we could try skipping time windows in order to keep up. There may be issues with other parts of the system which are expecting contiguous timestamps, however.

**Comment by eflumerf** [comment]
np04-srv-028 and np04-srv-029 can only handle 7 links each, for example. If we wanted to run with the full 40 links, we would need to prescale by at least a factor of 6.

**Comment by roland-sipos** [comment]
Skipping time-windows is not really an option for the parallel-post processing, as it would go against the main design principles. One could add a feature to skip frames, but then it would impact the algorithm. I think the only solution here is indeed to run fewer links by disabling the postprocessing step for selected links. 

Also, we know already based on our readout perf-evaluations that on the Cascade Lake hosts we won't manage to run 2 APAs with software TPG due to core count limitations.

**Comment by eflumerf** [comment]
OK, thanks @roland-sipos
